name: build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: Set execute permissions
        run: chmod +x ./test/test.bats

      # Run the script
      - name: Run script
        run: ./test/test.bats
